### ISSUE TITLE
Can't get the ledger value from another peer node

### ISSUE THREAD

**Issue by huhaiqing** [yeasy/docker-hyperledger-peer#1]
When created 2 hyperledger nodes in one host.
1.
docker run --name=vp0 \
                    --restart=unless-stopped \
                    -it \
                    -p 5000:5000 \
                    -p 30303:30303 \
                    -e CORE_PEER_ID=vp0 \
                    -e CORE_VM_ENDPOINT=http://172.17.0.1:4243 \
                    -e CORE_PEER_ADDRESSAUTODETECT=true \
                    -e CORE_NOOPS_BLOCK_TIMEOUT=10 \
                    yeasy/hyperledger-peer:noops peer peer

2.
docker run --name=vp1 --link vp0:vp0 \
                    --restart=unless-stopped \
                    -it \
                    -p 5001:5000 \
                    -p 40404:30303 \
                    -e CORE_PEER_ID=vp1 \
                    -e CORE_VM_ENDPOINT=http://172.17.0.1:4243 \
                    -e CORE_PEER_ADDRESSAUTODETECT=true \
                    -e CORE_NOOPS_BLOCK_TIMEOUT=10 \
                    yeasy/hyperledger-peer:noops peer peer
1. When I deployed the example in vp0, can't query the value form vp1.
   peer chaincode deploy -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'

peer chaincode invoke -n  f5ddbf58ce7828eafd7d42b0340fc42a6503b8b5cbf7295cc6fe06580cd6f9f5a01fe15a48d58df7ad62c806dabc226174db717639fe846f2d0eba7fa7666974 -c '{"Function": "invoke", "Args": ["a", "b", "10"]}'

peer chaincode query -n f5ddbf58ce7828eafd7d42b0340fc42a6503b8b5cbf7295cc6fe06580cd6f9f5a01fe15a48d58df7ad62c806dabc226174db717639fe846f2d0eba7fa7666974 -c '{"Function": "query", "Args": ["a"]}'

In vp0, query the value of a, it returns 90.
In vp1, can't query the value of a. it returns the chainnode f5ddbf58ce7828eafd7d42b0340fc42a6503b8b5cbf7295cc6fe06580cd6f9f5a01fe15a48d58df7ad62c806dabc226174db717639fe846f2d0eba7fa7666974 is not existed.

Could you tell us how to get the vaue in vp1?
Thanks in advance.

**Comment by yeasy** [comment]
Can u try the pbft consensus cluster, which is the recommended consensus.
See https://github.com/yeasy/docker-compose-files#hyperledger.
thanks!

**Comment by huhaiqing** [comment]
However, when I run the below command to run pbft consensus cluster, it can't get the value from the deployed node.
1. 
docker run --name=vp0 \
                    --restart=unless-stopped \
                    -it \
                    -p 5000:5000 \
                    -p 30303:30303 \
                    -e CORE_PEER_ID=vp0 \
                    -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 \
                    -e CORE_PEER_ADDRESSAUTODETECT=true \
                    -e CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft \
                    -e CORE_PBFT_GENERAL_MODE=classic \
                    -e CORE_PBFT_GENERAL_N=4 \
                    -e CORE_PBFT_GENERAL_TIMEOUT_REQUEST=10s \
                    yeasy/hyperledger-peer:pbft peer node start
2. peer chaincode deploy -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'
1. peer chaincode query -n 1edd7021ab71b766f4928a9ef91182c018dffb86fef7a4b5a5516ac590a87957e21a62d939df817f5105f524abddcddfc7b1a60d780f02d8235bd7af9db81b66 -c '{"Function": "query", "Args": ["a"]}'
   return Error, it says the container 1edd7021ab71b766f4928a9ef91182c018dffb86fef7a4b5a5516ac590a87957e21a62d939df817f5105f524abddcddfc7b1a60d780f02d8235bd7af9db81b66 is not existed.
   Can you tell me how fix the issue?
   Thanks !

**Comment by yeasy** [comment]
Please build up the 4 node cluster for pbft. 1 node is not allowed for pbft consensus.
See https://github.com/yeasy/docker-compose-files#hyperledger.
Thanks!
