### ISSUE TITLE
problems in #make all# in hyperledge

### ISSUE THREAD

**Issue by nobody4t** [yeasy/docker-hyperledger-peer#10]
I got this problem:

_Building build/image/ccenv/bin/protoc-gen-go
Unable to find image 'hyperledger/fabric-baseimage:s390x-0.2.0' locally
Pulling repository docker.io/hyperledger/fabric-baseimage
docker: Tag s390x-0.2.0 not found in repository docker.io/hyperledger/fabric-baseimage._

I wonder if this is due to the version change of hyperledger and the dockerfile is not updated.
Do you have any idea about why this error?

**Comment by yeasy** [comment]
Sorry, but where did you find the make all cmd in this Dockerfile?

Just from guess, you are building the fabric from source code? This is not recommended, as the latest branch is still changing quickly.

**Comment by nobody4t** [comment]
Yeah, you are right. I am trying to compile all the source code. 
OK, in this case, I wonder if there is any stable version so that I can deploy it and play with by myself.

**Comment by yeasy** [comment]
Please use the 0.6 branch.
