### ISSUE TITLE
What does this mean？

### ISSUE THREAD

**Issue by yangchas** [yeasy/docker-hyperledger-peer#11]
sudo docker daemon --api-cors-header="*" -H tcp://0.0.0.0:2375 -H unix:///var/run/docker. sock
How to customize the boot of win10 ?

**Comment by yeasy** [comment]
Well, currently I would like to recommend you use Docker on Linux, especially when you want to have something seriously.

**Comment by yangchas** [comment]
thanks！但是我运行在ubuntu下的时候，开机docker是自启的，status is running. Then stop the docker,now is  dead. Next,sudo docker daemon --api-cors-header="*" -H tcp://0.0.0.0:2375 -H unix:///var/run/docker. sock , docker status is failed.Can not start.Hint：job for docker.service failed because the control process exited with error code. See"systemctl status docker.service" and "journalctl -xe" for details. 
I don't know how to solve.

**Comment by yeasy** [comment]
Seems docker problem, are you using ubuntu 16.04 or 14.04?
