### ISSUE TITLE
Can the hyperleger value be readable from other network nodes?

### ISSUE THREAD

**Issue by huhaiqing** [yeasy/docker-hyperledger-peer#2]
Hi,

After deployed hyperledger docker peer, I can query the value among 4 docker nodes, these 4 docker container nodes run on the same virtual Host server.

My question is how to get the hyperledger value from other network nodes. For example, I init a hyperleger variable A to 100 in a docker server, the server is installed in Shanghai, I deployed another docker hyperledger server in Beijing, Can the server in Beijing query the value from Shanghai's server?

Could you tell us how to get the value from other network hyperledger peers?

Thanks in advance.

**Comment by yeasy** [comment]
First you need those nodes within the same cluster to connect to each other.

Since you have nodes on different locations, you may need to connect them through the internet.

**Comment by huhaiqing** [comment]
How to make the different locations to be the same cluster?

**Comment by yeasy** [comment]
There are lots of ways to achieve it.
The straightforward way is just to let each cluster reach others through the Internet, as well as computers.
