### ISSUE TITLE
Error building Peer container

### ISSUE THREAD

**Issue by polyrabbit** [yeasy/docker-hyperledger-peer#3]
Hi, thanks for providing this very useful Dockerfile, it saves me a lot of time to set up the develop environment.

I want to try the [`Local Run with chaincode testing`](https://github.com/yeasy/docker-hyperledger-peer#local-run-with-chaincode-testing) using `Noops consensus`, but when deploying chaincode, I encountered a problem says:

```
vp_1  | 16:16:06.507 [dockercontroller] Deploy -> ERRO 047 Error building Peer container: The command '/bin/sh -c go install github.com/hyperledger/fabric/examples/chaincod
e/go/chaincode_example02 && cp src/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/chaincode_example02 $GOPATH/bin/1edd7021ab71b766f4928a9ef91182
c018dffb86fef7a4b5a5516ac590a87957e21a62d939df817f5105f524abddcddfc7b1a60d780f02d8235bd7af9db81b66' returned a non-zero code: 127
```

I have no idea why this happened and how to solve it. Could you please help me or point out the right direction?

Many thanks!

**Comment by yeasy** [comment]
Could u make sure what IP:Port your docker daemon is listening on?

**Comment by yeasy** [comment]
Also, can you try:

``` sh
$ docker run --name=vp0 \
                    --restart=unless-stopped \
                    -it \
                    -p 5000:5000 \
                    -p 30303:30303 \
                    -v /var/run/docker.sock:/var/run/docker.sock \
                    -e CORE_PEER_ID=vp0 \
                    -e CORE_PEER_ADDRESSAUTODETECT=true \
                    -e CORE_NOOPS_BLOCK_TIMEOUT=10 \
                    yeasy/hyperledger-peer:noops peer node start
```

Which directly use local docker sock as the way.

**Comment by polyrabbit** [comment]
Thanks for your direction, I'm sure my docker0 bridge ip is `172.17.0.1` and I also tried to use local docker sock, but still without any luck.

Then I replayed all the steps in another server(redhat 7), and everything works fine, maybe the problem is my OS(Ubuntu 14.04). Anyway, I have a working environment for chaincode now.

Thanks for your help, closing...
