### ISSUE TITLE
The latest docker image does not include the file which include in the fabric trunk source code

### ISSUE THREAD

**Issue by huhaiqing** [yeasy/docker-hyperledger-peer#5]
Hi,

When use the "github.com/hyperledger/fabric/core/crypto/conf" and   "github.com/hyperledger/fabric/core/crypto/utils" to execute some ceritificate, I found that in the latest images, it does not include these source codes.

Could you help to build a new image to include the files which already included in the fabric source codes?

Thanks in advance

Regards
Harry

**Comment by yeasy** [comment]
Just update with latest code in master branch, please try pulling again later, thanks!
