### ISSUE TITLE
Error building images: The command '/bin/sh -c go install...' returned a non-zero code: 2

### ISSUE THREAD

**Issue by cophey** [yeasy/docker-hyperledger-peer#6]
deploy chaincode时，发生错误，如下：

> 15:10:29.070 [container] WriteGopathSrc -> INFO 018 rootDirectory = /opt/gopath/src
> 15:10:30.905 [crypto] InitClient -> INFO 019 Initializing client [jim]...
> 15:10:31.009 [crypto] InitClient -> INFO 01a Initializing client [jim]...done!
> 15:10:31.096 [crypto] closeClientInternal -> INFO 01b Closing client [jim]...
> 15:10:36.769 [dockercontroller] deployImage -> ERRO 01c Error building images: The command '/bin/sh -c go install github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 && cp src/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/chaincode_example02 $GOPATH/bin/021b7e32675adbe9be8c9e0fe01b9fff1fed6802333e3624389c7f95e272f5ac679c9df2480bc7a74976fa6dd108037c977d5c54915eb687ea9173381ab281c6' returned a non-zero code: 2
> 15:10:38.537 [dockercontroller] deployImage -> ERRO 01d Error building images: The command '/bin/sh -c go install github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 && cp src/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/chaincode_example02 $GOPATH/bin/021b7e32675adbe9be8c9e0fe01b9fff1fed6802333e3624389c7f95e272f5ac679c9df2480bc7a74976fa6dd108037c977d5c54915eb687ea9173381ab281c6' returned a non-zero code: 2
> 15:10:38.537 [chaincode] Launch -> ERRO 01e launchAndWaitForRegister failed Error starting container: The command '/bin/sh -c go install github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 && cp src/github.com/hyperledger/fabric/peer/core.yaml $GOPATH/bin && mv $GOPATH/bin/chaincode_example02 $GOPATH/bin/021b7e32675adbe9be8c9e0fe01b9fff1fed6802333e3624389c7f95e272f5ac679c9df2480bc7a74976fa6dd108037c977d5c54915eb687ea9173381ab281c6' returned a non-zero code: 2
> ![yt 1 8e9elfv 1 q aott g](https://cloud.githubusercontent.com/assets/7555270/18378555/46a2dc04-76a0-11e6-82e0-dda64c27b65c.png)

我的执行步骤：
1、ubuntu裸机安装hyperledger/fabric环境，如go、docker、rocksdb等，开发模式下测试chaincode的deploy、invoke、query，没有错误；
2、下载镜像

> docker pull busybox:latest
> docker pull hyperledger/fabric-membersrvc
> docker pull hyperledger/fabric-peer
> docker pull yeasy/hyperledger:latest
> docker tag yeasy/hyperledger:latest hyperledger/fabric-baseimage:latest

3、发布模式下运行hyperledger/fabric

> cd /opt/gopath/src/github.com/hyperledger/fabric/membersrvc/
> ./membersrvc
> 
> cd /opt/gopath/src/github.com/hyperledger/fabric/peer/
> CORE_SECURITY_ENABLED=true CORE_SECURITY_PRIVACY=false ./peer node start
> 
> cd /opt/gopath/src/github.com/hyperledger/fabric/peer/
> ./peer network login jim
> password：6avZQLwcUe9b
> 
> CORE_SECURITY_ENABLED=true CORE_SECURITY_PRIVACY=false ./peer chaincode deploy -u jim -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'

此时发生上述错误，且没有新的docker-image产生。

**Comment by yeasy** [comment]
Can u help post the command to start the network?
Thanks!

**Comment by cophey** [comment]
@yeasy 
the commands:

> cd /opt/gopath/src/github.com/hyperledger/fabric/membersrvc/
> ./membersrvc
> 
> cd /opt/gopath/src/github.com/hyperledger/fabric/peer/
> CORE_SECURITY_ENABLED=true CORE_SECURITY_PRIVACY=false ./peer node start
> 
> cd /opt/gopath/src/github.com/hyperledger/fabric/peer/
> ./peer network login jim
> password：6avZQLwcUe9b
> 
> CORE_SECURITY_ENABLED=true CORE_SECURITY_PRIVACY=false ./peer chaincode deploy -u jim -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02 -c '{"Function":"init", "Args": ["a","100", "b", "200"]}'

**Comment by yeasy** [comment]
@cophey I noticed that u are using two versions of the images.

Can u try with all images from community or from my repo?

e.g., you can remove these two commands:

``` sh
docker pull yeasy/hyperledger:latest
docker tag yeasy/hyperledger:latest hyperledger/fabric-baseimage:latest
```

**Comment by cophey** [comment]
@yeasy 
I use 'make all',rebuild my local image.And it's ok.
Thanks anyway.
