### ISSUE TITLE
Tag latest not found in repository yeasy/hyperledger-peer

### ISSUE THREAD

**Issue by yuanyuansiyuan** [yeasy/docker-hyperledger-peer#9]
when i use "docker pull yeasy/hyperledger-peer:latest". It came out that "FATA[0096] Tag latest not found in repository yeasy/hyperledger-peer",how can i fix this problem? Thank you for your time and patient!

**Comment by yeasy** [comment]
Can you retry?
It does work on my side.

By the way, you can try use yeasy/hyperledger-fabric.
